baseURL: "https://hectorlop.com"
languageCode: "en-us"
title: "Hector Lopez"
theme: "hugo-profile"
relativeURLs: true
publishDir: docs

googleanalytics: UA-167646412-8
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"

enableEmoji: true

# menus
Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /ew
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /34545
    #   parent: dropdown
    #   weight: 2

params:
  version: 3
  customCSS: false

  #favicon: "/images/fav.png"
  description: "A high performance hugo theme for personal portfolio and blog."

  # home
  disable_home: false
  profile_image: "/img/foto.jpeg"
  name: "Hector Lopez"
  namecolor: ffc107
  profession: "Machine Learning Researcher"
  github: "https://github.com/hectorLop"
  linkedin: "https://www.linkedin.com/in/hector-lopez-almazan-59b426146/"
  twitter: "https://twitter.com/hectorLop_"

  #Custom social links
  # customSocialLinks:
  #   - imageURL: "https://hugo-profile.netlify.app/images/fav.png"
  #     url: "https://gohugo.com"
  #   - fontAwesomeIconName: "fa fa-envelope"
  #     url: "https://gmail.com"
  
  # About
  disable_about: false
  descripe_l1_person: "I'm Hector, a Machine Learning Researcher at Instituto Tecnológico de Informática (ITI), working mainly on healthcare problems. Focused about applying ML to real world problems. Passionate about MLOps, to test, monitor, deploy and mantain ML models in production. Computer Science graduate and M.Sc. in Artificial Intelligence."
  #descripe_l2_person: "This is a example template for about section. You can find my works [here](#projects)"

  skills:
    - name: Python
      percentage: 90
    - name: Machine Learning
      percentage: 85
    - name: Deep Learning
      percentage: 80
    - name: Software Engineering
      percentage: 75

  # Experience
  disable_experience: yes
  experience:
    - company: "Google"
      # id: "google-developer"   // use this, when you want to change the id(used for navigation)
      role: "Software developer"
      startdate: Feb 2021
      enddate: present
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Facebook"
      # id: "facebook-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Mar 2020
      enddate: Dec 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.
    - company: "Amazon"
      # id: "amazon-developer" // use this, when you want to change the id(used for navigation)
      role: "Fullstack developer"
      startdate: Feb 2019
      enddate: Jan 2020
      featuredpoints:
        - point: Lead backend developer for a product.
        - point: Created a frontend design for a product.

  # Education
  disable_education: yes
  education:
    - degree: "B.tech"
      branch: "Information Technology"
      university: "Example university"
      startedyear: "2013"
      graduation: "2018"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"
    - degree: "Degree"
      branch: "Branch"
      university: "Example university"
      startedyear: "year"
      graduation: "year"

  # Projects
  disable_projects: false
  projects:
    - name: "Waste Detector"
      img: /img/waste_detector.png
      githublink: "https://github.com/hectorLop/Waste-Detector"
      featuredlink: "54.155.101.152:8501"
      description: "A deep learning-based system to detect waste in images and classify it according to which rubbish bin it must be thrown to be recycled."
    - name: "Weight&Biases Model Versioning"
      img: /img/weight_and_biases.png
      githublink: "https://github.com/hectorLop/Wandb-MV"
      description: "Model versioning using Weight&Biases"
    - name: "Soccer matches predictor"
      img: /img/soccer_prediction.jpg
      githublink: "https://github.com/hectorLop/SoccerPredictor"
      featuredlink: "https://github.com/hectorLop/SoccerPredictor"
      description: "This project serves a ML model to predict the outcome from the Spanish soccer league. It includes the set-up of all the infrastructure to deploy and train new models."
    - name: "CO2 emissions forecast"
      img: /img/co2_emissions_forecast.jpg
      githublink: "https://github.com/hectorLop/CO2_emissions_forecast"
      featuredlink: "https://github.com/hectorLop/CO2_emissions_forecast"
      description: "System to forecast the CO2 emissions related to electricity generation in Spain."

  # Achievements
  disable_achievements: yes
  achievements:
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
      # url: https://example.com
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg
    - title: Competition winner
      description: We are developed a product which can help others.
      img: /images/achiv.jpg

  # Contact
  disable_contact: true
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you!
  email: "lopez.almazan.hector@gmail.com"

  # Footer
  socialiconfooter: true
  recentposts: False

  # Blog
  showdescription: false
  tweet: true
